#:include Telas/menu_tela.kv
#:include Telas/mapa_tela.kv
#:include Telas/clientes_tela.kv
#:include Telas/busca_tela.kv
#:include Telas/info_tela.kv
#:include Telas/adicionar_cliente_tela.kv

<Gerenciador>:   
    Menu:
        name: 'Menu_tela'
    Mapa_tela:
        name: 'Mapa_tela'
    Clientes_tela:
        name: 'Clientes_tela'
    Busca_tela:
        name: 'Busca_tela'
    Info_tela:
        name: 'Info_tela'
    Adicionar_cliente_tela:
        name: 'Adicionar_cliente_tela'